DOMAIN = "polestar_api"
TIMEOUT = 90


CONF_VIN = "vin"

ACCESS_TOKEN_MANAGER_ID = "JWTh4Yf0b"
GRANT_TYPE = "password"
AUTHORIZATION = "Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc="

HEADER_AUTHORIZATION = "authorization"

CACHE_TIME = 30
